################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1, preferred, auto, auto
monitor=DP-1, preferred, auto-left, auto
monitor=,preferred,auto,auto, mirror, eDP1

# Ensure DP-3 is the primary monitor for XWayland (important for games for example)
exec-once = xrandr --output eDP-1 --primary
