################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1, preferred, auto, auto
monitor=DP-3, preferred, auto-up, auto
monitor=,preferred,auto,auto, mirror, eDP1

# Window settings
workspace = 1, monitor:DP-3, default:true
workspace = 2, monitor:DP-3
workspace = 5, monitor:DP-3


workspace = 3, monitor:eDP-1, default:true
workspace = 4, monitor:eDP-1

# Ensure DP-1 is the primary monitor for XWayland (important for games for example)
exec-once = xrandr --output DP-3 --primary
